# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eagleHome', '0002_contact'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact1',
        ),
    ]
