# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-19 14:09
from __future__ import unicode_literals

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('helpful', '0002_delete_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpful',
            name='video',
            field=embed_video.fields.EmbedVideoField(default=None),
        ),
    ]
